name: 'Backup sistema'
description: 'Faz backup do sistema atual'
inputs:
  server:
    description: 'Servidor onde será feito o backup'
    required: true
  user:
    description: 'Usuário com permissão no servidor'
    required: true
  pass:
    description: 'Senha do usuário'
    required: true
  project:
    description: 'Nome do projeto'
    required: true
  type:
    description: 'Tipo de projeto (ui/api/service/etc)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Configurando ambiente
      shell: bash
      run: |
          apt update
          apt install -y cifs-utils          

    - name: Preparando acesso ao servidor
      shell: bash
      run: |
        mkdir ~/backup
        mount -t cifs //$INPUT_SERVER/backup ~/backup -o username=${INPUT_USER},password=${INPUT_PASS},uid=$(id -u),gid=$(id -g)
        mkdir ~/win_share
        mount -t cifs //$INPUT_SERVER/sites ~/win_share -o username=${INPUT_USER},password=${INPUT_PASS},uid=$(id -u),gid=$(id -g)          
      env:
        INPUT_SERVER: ${{ inputs.server }}
        INPUT_USER: ${{ inputs.user }}
        INPUT_PASS: ${{ inputs.pass }}


    - name: Criando backup
      shell: bash
      run: |
        if [ "$(ls -A ~/win_share/$INPUT_PROJECT/$INPUT_TYPE)" ]; then
          current_date=$(date +"%Y%m%d_%H%M")
          nomepasta="${current_date}_${INPUT_PROJECT}_$INPUT_TYPE"

          mkdir ~/backup/$nomepasta && cp -r ~/win_share/$INPUT_PROJECT/$INPUT_TYPE/* "$_"
        else
          echo "A pasta está vazia, pulando a etapa de backup."
        fi          
      env:
        INPUT_PROJECT: ${{ inputs.project }}
        INPUT_TYPE: ${{ inputs.type }}
